{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\nallure.py:11: AssertionError"}, "description": "this test fails", "start": 1612252156195, "stop": 1612252156195, "uuid": "7a8aae04-01c9-477a-9dda-badc3afc8b53", "historyId": "795fd18a8246c309de8dfde73dd27a96", "testCaseId": "6d6a4997e97d5c4efb7504e1b0c25edd", "fullName": "allure#test_failure", "labels": [{"name": "suite", "value": "allure"}, {"name": "host", "value": "SC-202009151434"}, {"name": "thread", "value": "53232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "allure"}]}